In [3]:
import numpy as np
import scipy.io

In [2]:
#load data_subject_I.npy

data = np.load('data_subject_I.npy')

In [5]:
data

array([[-1.39391795, -0.49561   , -1.76625698, ..., -0.76615806,
        -0.23244562, -0.14687156],
       [ 0.53045415, -0.23248598,  0.35258046, ..., -0.00231856,
        -0.24648212, -0.42928428],
       [ 1.13308842,  0.33180387, -0.31458903, ...,  0.81599387,
         1.31184511,  1.38407545],
       ...,
       [-1.5389841 , -2.01615294, -1.86653802, ..., -0.53180136,
        -0.28571028,  0.37972915],
       [-0.8578087 , -0.38549941, -0.77768154, ...,  0.11137602,
        -0.0418572 ,  0.85104556],
       [ 0.34480094, -0.19645626, -0.7265258 , ..., -0.07650719,
        -0.11008846,  0.28848794]])

In [19]:
data = np.load('data/fmri/data_subject_I.npy')

In [20]:
data.shape

(1211, 25263)

In [3]:
mat_data = scipy.io.loadmat('story_features.mat')

Features of the dataset

In [4]:
#iterate through mat_data['features'] and print each feature
for i in mat_data['features']:
    print(i.dtype)
mat_data

[('type', 'O'), ('names', 'O'), ('values', 'O')]


{'__header__': b'MATLAB 5.0 MAT-file, Platform: MACI64, Created on: Thu Sep 25 18:45:34 2014',
 '__version__': '1.0',
 '__globals__': [],
 'features': array([[(array(['NNSE'], dtype='<U4'), array([[array(['s1000_1'], dtype='<U7'),
                 array(['s1000_10'], dtype='<U8'),
                 array(['s1000_15'], dtype='<U8'),
                 array(['s1000_21'], dtype='<U8'),
                 array(['s1000_30'], dtype='<U8'),
                 array(['s1000_48'], dtype='<U8'),
                 array(['s1000_66'], dtype='<U8'),
                 array(['s1000_72'], dtype='<U8'),
                 array(['s1000_75'], dtype='<U8'),
                 array(['s1000_82'], dtype='<U8'),
                 array(['s1000_97'], dtype='<U8'),
                 array(['s1000_98'], dtype='<U8'),
                 array(['s1000_117'], dtype='<U9'),
                 array(['s1000_132'], dtype='<U9'),
                 array(['s1000_135'], dtype='<U9'),
                 array(['s1000_163'], dtype='<U9'),


In [38]:
mat_data.keys()

dict_keys(['__header__', '__version__', '__globals__', 'features'])

In [39]:
mat_data['features']

array([[(array(['NNSE'], dtype='<U4'), array([[array(['s1000_1'], dtype='<U7'),
                array(['s1000_10'], dtype='<U8'),
                array(['s1000_15'], dtype='<U8'),
                array(['s1000_21'], dtype='<U8'),
                array(['s1000_30'], dtype='<U8'),
                array(['s1000_48'], dtype='<U8'),
                array(['s1000_66'], dtype='<U8'),
                array(['s1000_72'], dtype='<U8'),
                array(['s1000_75'], dtype='<U8'),
                array(['s1000_82'], dtype='<U8'),
                array(['s1000_97'], dtype='<U8'),
                array(['s1000_98'], dtype='<U8'),
                array(['s1000_117'], dtype='<U9'),
                array(['s1000_132'], dtype='<U9'),
                array(['s1000_135'], dtype='<U9'),
                array(['s1000_163'], dtype='<U9'),
                array(['s1000_170'], dtype='<U9'),
                array(['s1000_182'], dtype='<U9'),
                array(['s1000_197'], dtype='<U9'),
             

In [60]:
mat_data['features'][0][3]['values'][0].shape

(23,)

In [54]:
mat_data['features'][0][1]['values'].shape

(5176, 2)

In [55]:
feat_count = 0
for i in range(10):
    feat_count += mat_data['features'][0][i]['values'].shape[1]

feat_count

195

In [40]:
#get the size fo mat_data
mat_data['features'].shape

(1, 10)

In [6]:
#load the dat from data_subject_I.npy

data = np.load('data/fmri/data_subject_I.npy')



In [27]:
data.shape

(1211, 25263)

In [8]:
data.shape

(1211, 25263)

In [29]:
data

array([[-1.39391795, -0.49561   , -1.76625698, ..., -0.76615806,
        -0.23244562, -0.14687156],
       [ 0.53045415, -0.23248598,  0.35258046, ..., -0.00231856,
        -0.24648212, -0.42928428],
       [ 1.13308842,  0.33180387, -0.31458903, ...,  0.81599387,
         1.31184511,  1.38407545],
       ...,
       [-1.5389841 , -2.01615294, -1.86653802, ..., -0.53180136,
        -0.28571028,  0.37972915],
       [-0.8578087 , -0.38549941, -0.77768154, ...,  0.11137602,
        -0.0418572 ,  0.85104556],
       [ 0.34480094, -0.19645626, -0.7265258 , ..., -0.07650719,
        -0.11008846,  0.28848794]])

In [4]:
#load the words_fmri.npy

words = np.load('data/fmri/words_fmri.npy')

In [11]:
words.shape

(5176,)

In [31]:
#store words in a text file

np.savetxt('words.txt', words, fmt='%s')

In [5]:
#load the time_words.npy

time_words = np.load('data/fmri/time_words_fmri.npy')

In [6]:
time_words

array([  20. ,   20.5,   21. , ..., 2692. , 2692.5, 2693. ])

In [7]:
#put time words in a text file

np.savetxt('time_words.txt', time_words, fmt='%s')

In [9]:
#iterate through time_words until you find values that are more than 0.5 apart

temp = time_words[0]
for i in time_words:
    if i - temp > 0.5:
        print(i)
    temp = i


700.0
1404.0
1962.0


In [1]:
time_words

NameError: name 'time_words' is not defined

In [33]:
time_words.shape

(5176,)

In [35]:
5176/4

1294.0

In [25]:
#store time_words into a text file
# till the second decimal place
np.savetxt('time_words.txt', time_words, fmt='%.2f')


In [15]:
5176/4

1294.0

In [16]:
#load the time_fmri.npy

time_fmri = np.load('data/fmri/time_fmri.npy')

In [18]:
time_fmri.shape

(1351,)

In [22]:
time_fmri

array([   0,    2,    4, ..., 2696, 2698, 2700], dtype=uint16)

In [28]:
time_fmri.shape

(1351,)

In [19]:
#load the runs_fmri.npy

runs_fmri = np.load('data/fmri/runs_fmri.npy') 


In [21]:
runs_fmri.shape

(1351,)

In [32]:
runs_fmri

array([1, 1, 1, ..., 4, 4, 4], dtype=uint16)